<?php
/**
 * Yii2 extension for payment processing with Omnipay, Payum and more later.
 *
 * @link      https://github.com/hiqdev/yii2-merchant
 * @package   yii2-merchant
 * @license   BSD-3-Clause
 * @copyright Copyright (c) 2015-2017, HiQDev (http://hiqdev.com/)
 */

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Sum' => 'Сумма',
    'Available payment methods' => 'Доступные методы оплаты',
    'Enter the amount of the replenishment in dollars. For example: 8.79' => 'Введите сумму пополнения в долларах. Например: 8,79',
    'Important information' => 'Важная информация',
    'Select payment method' => 'Выберите способ оплаты',
    'We support fully automatic account depositing with the following payment systems: {merchants}' => 'Мы принимаем к оплате в автоматическом режиме следующие платежные системы: {merchants}',
    'Remember to return to the site after successful payment!' => 'Не забудьте вернуться на сайт после успешной оплаты!',
    'Pay {amount} with {merchantLabel}' => 'Оплатить {amount} через {merchantLabel}',
    'Proceed' => 'Продолжить',
    'Recharge account' => 'Пополнить счёт',
    'Account recharging' => 'Пополнение счёта',
    'Waiting for confirmation from the payment system...' => 'Ожидаем подтверждения из платежной системы...',
    'Payment result' => 'Результат оплаты',
    'There are no payments methods available' => 'Нет доступных методов оплаты',
    'Amount' => 'Сумма',
    'Name' => 'Название',
    'Payment System' => 'Платежная система',
    'Purse' => 'Кошелек',
    'Fee' => 'Комиссия платежной системы',
    'Currency' => 'Валюта',
    'Signature' => 'Подпись',
    'Commission' => 'Комиссия',
    'Payment failed or cancelled' => 'Платеж прошел неуспешно или был отменён',
    'including commission {commission}' => 'включая комиссию {commission}',
    'including VAT {rate}% &mdash; {sum}' => 'включая НДС {rate}% &mdash; {sum}',
];
